Armoury:add_item(1, 1, "RIFLE")
Armoury:add_item(16, 0, "HIGH EXPLOSIVE")
Armoury:add_item(10, 6, "ROCKET LAUNCHER")
Armoury:add_item(8, 1, "Heavy Plasma")
Armoury:add_item(15, 0, "Flare")
Armoury:add_item(14, 0, "SMOKE GRENADE")
Armoury:add_item(13, 0, "PROXIMITY GRENADE")
Armoury:add_item(12, 0, "GRENADE")
Armoury:add_item(11, 0, "ALIEN GRENADE")
Armoury:add_item(8, 0, "Heavy Plasma Clip")
Armoury:add_item(7, 0, "Plasma Rifle Clip")
Armoury:add_item(7, 1, "Plasma Rifle")
Armoury:add_item(6, 0, "Plasma Pistol Clip")
Armoury:add_item(6, 1, "Plasma Pistol")
Armoury:add_item(18, 6, "BLASTER BOMB")
Armoury:add_item(16, 6, "BLASTER LAUNCHER")
Armoury:add_item(14, 6, "SMALL ROCKET")
Armoury:add_item(13, 6, "LARGE ROCKET")
Armoury:add_item(12, 6, "INCENDIARY ROCKET")
Armoury:add_item(2, 7, "AUTO-CANNON I-AMMO")
Armoury:add_item(2, 6, "AUTO-CANNON HE-AMMO")
Armoury:add_item(7, 7, "CANNON I-AMMO")
Armoury:add_item(7, 8, "CANNON AP-AMMO")
Armoury:add_item(7, 6, "CANNON HE-AMMO")
Armoury:add_item(5, 6, "HEAVY CANNON")
Armoury:add_item(4, 1, "HEAVY LASER")
Armoury:add_item(3, 1, "LASER GUN")
Armoury:add_item(2, 1, "LASER PISTOL")
Armoury:add_item(1, 0, "RIFLE CLIP")
Armoury:add_item(2, 8, "AUTO-CANNON AP-AMMO")
Armoury:add_item(0, 6, "AUTO-CANNON")
Armoury:add_item(0, 0, "PISTOL CLIP")
Armoury:add_item(0, 1, "PISTOL")
Armoury:add_item(19, 3, "PSI-AMP")
Armoury:add_item(17, 3, "MIND PROBE")
Armoury:add_item(19, 0, "MOTION SCANNER")
Armoury:add_item(18, 0, "MEDI-KIT")
Armoury:add_item(14, 3, "SMALL LAUNCHER")
Armoury:add_item(14, 2, "STUN MISSILE")
Armoury:add_item(13, 2, "STUN ROD")
