CREATE TABLE ufo2000_users (name text primary key, password text, last_login date, victories integer default 0, draws integer default 0, defeats integer default 0, elo_score double default 1500);
CREATE TABLE ufo2000_sequences (name text primary key,seq_val integer);
CREATE TABLE ufo2000_games (id integer primary key,  last_received_packed integer, is_finished text, errors text, result integer);
CREATE TABLE ufo2000_game_players(game integer,  player text, last_sended_packet integer, position integer, primary key(game, player));
insert or ignore into ufo2000_sequences values ('ufo2000_games',0);
CREATE TABLE ufo2000_game_packets(game integer, id integer, sender integer, command text, packet_type integer, primary key(game,id));
CREATE TRIGGER ufo2000_game_insert insert ON ufo2000_games BEGIN 
    delete from ufo2000_game_packets where game<new.id-100; 
    delete from ufo2000_debug_log where game<new.id-100; 
END;
pragma autovacuum=on;
alter table ufo2000_games add column client_version text;
alter table ufo2000_game_packets add column time real;
create table ufo2000_user_sessions (id integer primary key, user text, realm text, system text, version text, begin real, end real, unique (user, begin));
alter table ufo2000_user_sessions add column realm text;
alter table ufo2000_user_sessions add column system text;
alter table ufo2000_user_sessions add column version text;
alter table ufo2000_game_packets add column session integer;
insert or ignore into ufo2000_sequences values ('ufo2000_user_sessions', 0);
create table ufo2000_debug_packets (game integer, id integer, sender integer, time real, param text, value text, session integer, primary key (game, id));
create table ufo2000_debug_log (game integer, session integer, sender integer, id integer, time real, type integer, value text);
create index ufo2000_debug_log_indx on ufo2000_debug_log (game, session, sender, id, type);
create index ufo2000_debug_packets_indx on ufo2000_debug_packets (session, game, param);