------------------------------------------------------------------------------
-- Original TFTD Weapons Set (by DiversanT)
------------------------------------------------------------------------------

AddXcomItem {
	cost = 0,
	name = "DART PISTOL",
	pInv = pck_image_ex(true, 32, 48, "$(tftd)/units/bigobs.pck", 3),
	pMap = pck_image_ex(true, 32, 48, "$(tftd)/units/floorob.pck", 3),
	health = 999,
	importance = 5,
	width = 1,
	height = 2,
	ammo = {"DART POD"},
	pHeld = pck_image_set_ex(true, 32, 40, "$(tftd)/units/handob.pck", 96, 8),
	accuracy = {0, 40, 80},
	time = {0, 20, 50},
	weight = 5,
	isGun = 1,
	minimapMark = 1,
	sound = "cv-pistol-shot",
}

AddXcomItem {
	cost = 0,
	name = "DART POD",
	pInv = pck_image_ex(true, 32, 48, "$(tftd)/units/bigobs.pck", 4),
	pMap = pck_image_ex(true, 32, 48, "$(tftd)/units/floorob.pck", 4),
	health = 999,
	damage = 16,
	dDeviation = 100,
	importance = 3,
	width = 1,
	height = 1,
	pHeld = pck_image_set_ex(true, 32, 40, "$(tftd)/units/handob.pck", 240, 8),
	damageType = 0,
	rounds = 12,
	disappear = 1,
	weight = 2,
	isAmmo = 1,
	reloadTime = 15,
	sound = "cv-bullet-hit",
}

AddXcomItem {
	cost = 50,
	name = "HARPOON GUN",
	pInv = pck_image_ex(true, 32, 48, "$(tftd)/units/bigobs.pck", 1),
	pMap = pck_image_ex(true, 32, 48, "$(tftd)/units/floorob.pck", 1),
	health = 999,
	importance = 6,
	width = 1,
	height = 3,
	ammo = {"HARPOON POD"},
	pHeld = pck_image_set_ex(true, 32, 40, "$(tftd)/units/handob.pck", 0, 8),
	accuracy = {40, 60, 90},
	time = {13, 25, 80},
	autoShots = 3,
	weight = 8,
	isGun = 1,
	minimapMark = 1,
	twoHanded = 1,
	sound = "cv-rifle-shot",
}

AddXcomItem {
	cost = 20,
	name = "HARPOON POD",
	pInv = pck_image_ex(true, 32, 48, "$(tftd)/units/bigobs.pck", 2),
	pMap = pck_image_ex(true, 32, 48, "$(tftd)/units/floorob.pck", 2),
	health = 999,
	damage = 32,
	dDeviation = 100,
	importance = 1,
	width = 1,
	height = 1,
	pHeld = pck_image_set_ex(true, 32, 40, "$(tftd)/units/handob.pck", 248, 8),
	damageType = 0,
	rounds = 10,
	disappear = 1,
	weight = 2,
	isAmmo = 1,
	reloadTime = 15,
	sound = "cv-bullet-hit",
}

AddXcomItem {
	cost = 80,
	name = "GAS CANNON",
	pInv = pck_image_ex(true, 32, 48, "$(tftd)/units/bigobs.pck", 11),
	pMap = pck_image_ex(true, 32, 48, "$(tftd)/units/floorob.pck", 11),
	health = 999,
	importance = 14,
	width = 2,
	height = 3,
	ammo = {"SOLID BOLT", "EXPLOSIVE BOLT", "PHOSPHOROUS BOLT"},
	pHeld = pck_image_set_ex(true, 32, 40, "$(tftd)/units/handob.pck", 24, 8),
	accuracy = {0, 60, 90},
	time = {0, 40, 75},
	weight = 17,
	isGun = 1,
	minimapMark = 1,
	twoHanded = 1,
	sound = "cv-heavy-cannon-shot",
}

AddXcomItem {
	cost = 60,
	name = "SOLID BOLT",
	pInv = pck_image_ex(true, 32, 48, "$(tftd)/units/bigobs.pck", 12),
	pMap = pck_image_ex(true, 32, 48, "$(tftd)/units/floorob.pck", 8),
	health = 999,
	damage = 60,
	dDeviation = 100,
	importance = 4,
	width = 2,
	height = 1,
	pHeld = pck_image_set_ex(true, 32, 40, "$(tftd)/units/handob.pck", 272, 8),
	damageType = 0,
	rounds = 8,
	disappear = 1,
	weight = 5,
	isAmmo = 1,
	reloadTime = 15,
	sound = "cv-cannon-AP-hit",
}

AddXcomItem {
	cost = 80,
	name = "EXPLOSIVE BOLT",
	pInv = pck_image_ex(true, 32, 48, "$(tftd)/units/bigobs.pck", 13),
	pMap = pck_image_ex(true, 32, 48, "$(tftd)/units/floorob.pck", 9),
	health = 999,
	damage = 65,
	dDeviation = 100,
	exploRange = 3,
	smokeRange = 3,
	smokeTime = 2,
	importance = 4,
	width = 2,
	height = 1,
	pHeld = pck_image_set_ex(true, 32, 40, "$(tftd)/units/handob.pck", 256, 8),
	damageType = 2,
	rounds = 8,
	disappear = 1,
	weight = 6,
	isAmmo = 1,
	reloadTime = 15,
	sound = "cv-cannon-HE-hit",
}

AddXcomItem {
	cost = 70,
	name = "PHOSPHOROUS BOLT",
	pInv = pck_image_ex(true, 32, 48, "$(tftd)/units/bigobs.pck", 14),
	pMap = pck_image_ex(true, 32, 48, "$(tftd)/units/floorob.pck", 10),
	health = 999,
	damage = 60,
	dDeviation = 100,
	exploRange = 3,
	smokeRange = 3,
	smokeTime = 2,
	importance = 4,
	width = 2,
	height = 1,
	pHeld = pck_image_set_ex(true, 32, 40, "$(tftd)/units/handob.pck", 264, 8),
	damageType = 1,
	rounds = 8,
	disappear = 1,
	weight = 6,
	isAmmo = 1,
	reloadTime = 15,
	sound = "cv-cannon-IN-hit",
}

AddXcomItem {
	cost = 100,
	name = "HYDRO JET CANNON",
	pInv = pck_image_ex(true, 32, 48, "$(tftd)/units/bigobs.pck", 7),
	pMap = pck_image_ex(true, 32, 48, "$(tftd)/units/floorob.pck", 7),
	health = 999,
	importance = 16,
	width = 2,
	height = 3,
	ammo = {"AP-SHELL", "HE-SHELL", "PHOSPHOROUS-SHELL"},
	pHeld = pck_image_set_ex(true, 32, 40, "$(tftd)/units/handob.pck", 32, 8),
	accuracy = {40, 50, 80},
	time = {13, 35, 80},
	autoShots = 3,
	weight = 19,
	isGun = 1,
	minimapMark = 1,
	twoHanded = 1,
	sound = "cv-auto-cannon-shot",
}

AddXcomItem {
	cost = 50,
	name = "AP-SHELL",
	pInv = pck_image_ex(true, 32, 48, "$(tftd)/units/bigobs.pck", 8),
	pMap = pck_image_ex(true, 32, 48, "$(tftd)/units/floorob.pck", 13),
	health = 999,
	damage = 40,
	dDeviation = 100,
	importance = 4,
	width = 2,
	height = 1,
	pHeld = pck_image_set_ex(true, 32, 40, "$(tftd)/units/handob.pck", 296, 8),
	damageType = 0,
	rounds = 12,
	disappear = 1,
	weight = 5,
	isAmmo = 1,
	reloadTime = 15,
	sound = "cv-cannon-AP-hit",
}

AddXcomItem {
	cost = 100,
	name = "HE-SHELL",
	pInv = pck_image_ex(true, 32, 48, "$(tftd)/units/bigobs.pck", 9),
	pMap = pck_image_ex(true, 32, 48, "$(tftd)/units/floorob.pck", 14),
	health = 999,
	damage = 50,
	dDeviation = 100,
	exploRange = 3,
	smokeRange = 3,
	smokeTime = 2,
	importance = 4,
	width = 2,
	height = 1,
	pHeld = pck_image_set_ex(true, 32, 40, "$(tftd)/units/handob.pck", 280, 8),
	damageType = 2,
	rounds = 12,
	disappear = 1,
	weight = 5,
	isAmmo = 1,
	reloadTime = 15,
	sound = "cv-cannon-HE-hit",
}

AddXcomItem {
	cost = 90,
	name = "PHOSPHOROUS-SHELL",
	pInv = pck_image_ex(true, 32, 48, "$(tftd)/units/bigobs.pck", 10),
	pMap = pck_image_ex(true, 32, 48, "$(tftd)/units/floorob.pck", 12),
	health = 999,
	damage = 40,
	dDeviation = 100,
	exploRange = 3,
	smokeRange = 3,
	smokeTime = 2,
	importance = 4,
	width = 2,
	height = 1,
	pHeld = pck_image_set_ex(true, 32, 40, "$(tftd)/units/handob.pck", 288, 8),
	damageType = 1,
	rounds = 12,
	disappear = 1,
	weight = 5,
	isAmmo = 1,
	reloadTime = 15,
	sound = "cv-cannon-IN-hit",
}

AddXcomItem {
	cost = 100,
	name = "AQUA JET LAUNCHER",
	pInv = pck_image_ex(true, 32, 48, "$(tftd)/units/bigobs.pck", 15),
	pMap = pck_image_ex(true, 32, 48, "$(tftd)/units/floorob.pck", 15),
	health = 999,
	importance = 18,
	width = 2,
	height = 3,
	ammo = {"SMALL TORPEDO", "LARGE TORPEDO", "PHOSPHOROUS TORPEDO"},
	pHeld = pck_image_set_ex(true, 32, 40, "$(tftd)/units/handob.pck", 72, 8),
	accuracy = {0, 50, 110},
	time = {0, 40, 80},
	weight = 10,
	isGun = 1,
	minimapMark = 1,
	twoHanded = 1,
	sound = "rl-launch",
}

AddXcomItem {
	cost = 200,
	name = "SMALL TORPEDO",
	pInv = pck_image_ex(true, 32, 48, "$(tftd)/units/bigobs.pck", 16),
	pMap = pck_image_ex(true, 32, 48, "$(tftd)/units/floorob.pck", 16),
	health = 999,
	damage = 80,
	dDeviation = 100,
	exploRange = 4,
	smokeRange = 4,
	smokeTime = 2,
	importance = 5,
	width = 1,
	height = 3,
	pHeld = pck_image_set_ex(true, 32, 40, "$(tftd)/units/handob.pck", 304, 8),
	damageType = 2,
	rounds = 1,
	disappear = 1,
	weight = 5,
	isAmmo = 1,
	reloadTime = 15,
	sound = "small-rocket-hit",
}

AddXcomItem {
	cost = 300,
	name = "LARGE TORPEDO",
	pInv = pck_image_ex(true, 32, 48, "$(tftd)/units/bigobs.pck", 17),
	pMap = pck_image_ex(true, 32, 48, "$(tftd)/units/floorob.pck", 17),
	health = 999,
	damage = 90,
	dDeviation = 100,
	exploRange = 6,
	smokeRange = 6,
	smokeTime = 2,
	importance = 6,
	width = 1,
	height = 3,
	pHeld = pck_image_set_ex(true, 32, 40, "$(tftd)/units/handob.pck", 312, 8),
	damageType = 2,
	rounds = 1,
	disappear = 1,
	weight = 8,
	isAmmo = 1,
	reloadTime = 15,
	sound = "HE-rocket-hit",
}

AddXcomItem {
	cost = 250,
	name = "PHOSPHOROUS TORPEDO",
	pInv = pck_image_ex(true, 32, 48, "$(tftd)/units/bigobs.pck", 18),
	pMap = pck_image_ex(true, 32, 48, "$(tftd)/units/floorob.pck", 18),
	health = 999,
	damage = 80,
	dDeviation = 100,
	exploRange = 5,
	smokeRange = 5,
	smokeTime = 2,
	importance = 7,
	width = 1,
	height = 3,
	pHeld = pck_image_set_ex(true, 32, 40, "$(tftd)/units/handob.pck", 320, 8),
	damageType = 1,
	rounds = 1,
	disappear = 1,
	weight = 8,
	isAmmo = 1,
	reloadTime = 15,
	sound = "IN-rocket-hit",
}

AddXcomItem {
	cost = 150,
	name = "GAUSS PISTOL",
	pInv = pck_image_ex(true, 32, 48, "$(tftd)/units/bigobs.pck", 5),
	pMap = pck_image_ex(true, 32, 48, "$(tftd)/units/floorob.pck", 5),
	health = 999,
	importance = 4,
	width = 1,
	height = 2,
	pHeld = pck_image_set_ex(true, 32, 40, "$(tftd)/units/handob.pck", 128, 8),
	ammo = {"GAUSS PISTOL CLIP"},
	accuracy = {20, 40, 70},
	time = {10, 25, 50},
	autoShots = 3,
	weight = 7,
	isGun = 1,
	minimapMark = 1,	
	sound = "laser-pistol-shot",
}

AddXcomItem {
	cost = 25,
	name = "GAUSS PISTOL CLIP",
	pInv = pck_image_ex(true, 32, 48, "$(tftd)/units/bigobs.pck", 57),
	pMap = pck_image_ex(true, 32, 48, "$(tftd)/units/floorob.pck", 78),
	health = 999,
	damage = 45,
	dDeviation = 100,
	importance = 3,
	width = 1,
	height = 1,
	pHeld = pck_image_set_ex(true, 32, 40, "$(tftd)/units/handob.pck", 216, 8),
	damageType = 0,
	rounds = 20,
	disappear = 1,
	weight = 2,
	isAmmo = 1,
	reloadTime = 15,
	sound = "plasma-hit",
}

AddXcomItem {
	cost = 250,
	name = "GAUSS RIFLE",
	pInv = pck_image_ex(true, 32, 48, "$(tftd)/units/bigobs.pck", 0),
	pMap = pck_image_ex(true, 32, 48, "$(tftd)/units/floorob.pck", 0),
	health = 999,
	importance = 7,
	width = 1,
	height = 3,
	pHeld = pck_image_set_ex(true, 32, 40, "$(tftd)/units/handob.pck", 8, 8),
	ammo = {"GAUSS RIFLE CLIP"},
	accuracy = {50, 65, 100},
	time = {13, 30, 60},
	autoShots = 3,
	weight = 8,
	isGun = 1,
	minimapMark = 1,
	twoHanded = 1,
	sound = "laser-rifle-shot",
}

AddXcomItem {
	cost = 50,
	name = "GAUSS RIFLE CLIP",
	pInv = pck_image_ex(true, 32, 48, "$(tftd)/units/bigobs.pck", 61),
	pMap = pck_image_ex(true, 32, 48, "$(tftd)/units/floorob.pck", 78),
	health = 999,
	damage = 60,
	dDeviation = 100,
	importance = 3,
	width = 1,
	height = 1,
	pHeld = pck_image_set_ex(true, 32, 40, "$(tftd)/units/handob.pck", 224, 8),
	damageType = 0,
	rounds = 15,
	disappear = 1,
	weight = 3,
	isAmmo = 1,
	reloadTime = 15,
	sound = "plasma-hit",
}

AddXcomItem {
	cost = 200,
	name = "HEAVY GAUSS CANNON",
	pInv = pck_image_ex(true, 32, 48, "$(tftd)/units/bigobs.pck", 6),
	pMap = pck_image_ex(true, 32, 48, "$(tftd)/units/floorob.pck", 6),
	health = 999,
	importance = 12,
	width = 2,
	height = 3,
	pHeld = pck_image_set_ex(true, 32, 40, "$(tftd)/units/handob.pck", 16, 8),
	ammo = {"GAUSS CANNON CLIP"},
	accuracy = {0, 50, 90},
	time = {0, 40, 80},
	weight = 18,
	isGun = 1,
	minimapMark = 1,
	twoHanded = 1,
	sound = "laser-heavy-shot",
}

AddXcomItem {
	cost = 50,
	name = "GAUSS CANNON CLIP",
	pInv = pck_image_ex(true, 32, 48, "$(tftd)/units/bigobs.pck", 62),
	pMap = pck_image_ex(true, 32, 48, "$(tftd)/units/floorob.pck", 78),
	health = 999,
	damage = 75,
	dDeviation = 100,
	importance = 3,
	width = 1,
	height = 1,
	pHeld = pck_image_set_ex(true, 32, 40, "$(tftd)/units/handob.pck", 232, 8),
	damageType = 0,
	rounds = 10,
	disappear = 1,
	weight = 3,
	isAmmo = 1,
	reloadTime = 15,
	sound = "plasma-hit",
}

AddXcomItem {
	cost = 70,
	name = "MAGNA-BLAST GRENADE",
	pInv = pck_image_ex(true, 32, 48, "$(tftd)/units/bigobs.pck", 19),
	pMap = pck_image_ex(true, 32, 48, "$(tftd)/units/floorob.pck", 19),      
	health = 999,
	damage = 50,
	dDeviation = 100,
	exploRange = 5,
	smokeRange = 5,
	smokeTime = 2,
	importance = 1,
	width = 1,
	height = 1,
	pHeld = pck_image_set_ex(true, 32, 40, "$(tftd)/units/handob.pck", 120, 8),
	damageType = 2,
	isGrenade = 1,
	weight = 3,
}

AddXcomItem {
	cost = 20,
	name = "DYE GRENADE",
	pInv = pck_image_ex(true, 32, 48, "$(tftd)/units/bigobs.pck", 20),
	pMap = pck_image_ex(true, 32, 48, "$(tftd)/units/floorob.pck", 19),
	health = 999,
	exploRange = 0,
	smokeRange = 5,
	smokeTime = 2,
	importance = 1,
	width = 1,
	height = 1,
	pHeld = pck_image_set_ex(true, 32, 40, "$(tftd)/units/handob.pck", 120, 8),
	damageType = 2,
	isGrenade = 1,
	weight = 3,
}

AddXcomItem {
	cost = 80,
	name = "PARTICLE GRENADE",
	pInv = pck_image_ex(true, 32, 48, "$(tftd)/units/bigobs.pck", 21),
	pMap = pck_image_ex(true, 32, 48, "$(tftd)/units/floorob.pck", 21),
	health = 999,
	damage = 70,
	dDeviation = 100,
	exploRange = 6,
	smokeRange = 6,
	smokeTime = 2,
	importance = 1,
	width = 1,
	height = 1,
	pHeld = pck_image_set_ex(true, 32, 40, "$(tftd)/units/handob.pck", 120, 8),
	damageType = 2,
	isGrenade = 1,
	isProximityGrenade = 1,
	weight = 3,
}

AddXcomItem {
	cost = 105,
	name = "MAGNA-PACK",
	pInv = pck_image_ex(true, 32, 48, "$(tftd)/units/bigobs.pck", 22),
	pMap = pck_image_ex(true, 32, 48, "$(tftd)/units/floorob.pck", 22),
	health = 999,
	damage = 100,
	dDeviation = 100,
	exploRange = 6,
	smokeRange = 6,
	smokeTime = 2,
	importance = 4,
	width = 2,
	height = 1,
	pHeld = pck_image_set_ex(true, 32, 40, "$(tftd)/units/handob.pck", 352, 8),
	damageType = 2,
	isGrenade = 1,
	isHighExplosive = 1,
	weight = 6,
}

AddXcomItem {
	cost = 100,
	name = "THERMAL TAZER",
	pInv = pck_image_ex(true, 32, 48, "$(tftd)/units/bigobs.pck", 26),
	pMap = pck_image_ex(true, 32, 48, "$(tftd)/units/floorob.pck", 26),
	health = 999,
	damage = 100,
	dDeviation = 100,
	importance = 6,
	width = 1,
	height = 3,
	pHeld = pck_image_set_ex(true, 32, 40, "$(tftd)/units/handob.pck", 152, 8),
	useTime = 25,
	damageType = 5,
	weight = 6,
	isHandToHand = 1,
	twoHanded = 1,
}

AddXcomItem {
	cost = 450,
	name = "SONIC CANNON",
	pInv = pck_image_ex(true, 32, 48, "$(tftd)/units/bigobs.pck", 30),
	pMap = pck_image_ex(true, 32, 48, "$(tftd)/units/floorob.pck", 29),
	health = 999,
	importance = 10,
	width = 2,
	height = 3,
	ammo = {"SONIC CANNON CLIP"},
	pHeld = pck_image_set_ex(true, 32, 40, "$(tftd)/units/handob.pck", 40, 8),
	accuracy = {0, 80, 115},
	time = {0, 50, 70},
	weight = 8,
	isGun = 1,
	minimapMark = 1,
	twoHanded = 1,
	sound = "plasma-heavy-shot",
}

AddXcomItem {
	cost = 150,
	name = "SONIC CANNON CLIP",
	pInv = pck_image_ex(true, 32, 48, "$(tftd)/units/bigobs.pck", 25),
	pMap = pck_image_ex(true, 32, 48, "$(tftd)/units/floorob.pck", 33),
	health = 999,
	damage = 130,
	dDeviation = 100,
	importance = 1,
	width = 1,
	height = 1,
	pHeld = pck_image_set_ex(true, 32, 40, "$(tftd)/units/handob.pck", 200, 8),
	damageType = 4,
	rounds = 10,
	disappear = 1,
	weight = 3,
	isAmmo = 1,
	reloadTime = 15,
	sound = "plasma-hit",
}

AddXcomItem {
	cost = 350,
	name = "SONIC BLASTA RIFLE",
	pInv = pck_image_ex(true, 32, 48, "$(tftd)/units/bigobs.pck", 31),
	pMap = pck_image_ex(true, 32, 48, "$(tftd)/units/floorob.pck", 30),
	health = 999,
	importance = 6,
	width = 1,
	height = 3,
	ammo = {"BLASTA CLIP"},
	pHeld = pck_image_set_ex(true, 32, 40, "$(tftd)/units/handob.pck", 48, 8),
	accuracy = {0, 75, 110},
	time = {0, 40, 60},
	weight = 5,
	isGun = 1,
	minimapMark = 1,
	twoHanded = 1,
	sound = "plasma-rifle-shot",
}

AddXcomItem {
	cost = 100,
	name = "BLASTA CLIP",
	pInv = pck_image_ex(true, 32, 48, "$(tftd)/units/bigobs.pck", 41),
	pMap = pck_image_ex(true, 32, 48, "$(tftd)/units/floorob.pck", 33),
	health = 999,
	damage = 95,
	dDeviation = 100,
	importance = 1,
	width = 1,
	height = 1,
	pHeld = pck_image_set_ex(true, 32, 40, "$(tftd)/units/handob.pck", 432, 8),
	damageType = 4,
	rounds = 15,
	disappear = 1,
	weight = 3,
	isAmmo = 1,
	reloadTime = 15,
	sound = "plasma-hit",
}

AddXcomItem {
	cost = 200,
	name = "SONIC PISTOL",
	pInv = pck_image_ex(true, 32, 48, "$(tftd)/units/bigobs.pck", 32),
	pMap = pck_image_ex(true, 32, 48, "$(tftd)/units/floorob.pck", 31),
	health = 999,
	importance = 4,
	width = 1,
	height = 2,
	ammo = {"SONIC PISTOL CLIP"},
	pHeld = pck_image_set_ex(true, 32, 40, "$(tftd)/units/handob.pck", 144, 8),
	accuracy = {0, 65, 85},
	time = {0, 30, 50},
	weight = 3,
	isGun = 1,
	minimapMark = 1,
	sound = "plasma-pistol-shot",
}

AddXcomItem {
	cost = 50,
	name = "SONIC PISTOL CLIP",
	pInv = pck_image_ex(true, 32, 48, "$(tftd)/units/bigobs.pck", 34),
	pMap = pck_image_ex(true, 32, 48, "$(tftd)/units/floorob.pck", 33),
	health = 999,
	damage = 80,
	dDeviation = 100,
	importance = 1,
	width = 1,
	height = 1,
	pHeld = pck_image_set_ex(true, 32, 40, "$(tftd)/units/handob.pck", 424, 8),
	damageType = 4,
	rounds = 20,
	disappear = 1,
	weight = 3,
	isAmmo = 1,
	reloadTime = 15,
	sound = "plasma-hit",
}

AddXcomItem {
	cost = 300,
	name = "THERMAL SHOK CANNON",
	pInv = pck_image_ex(true, 32, 48, "$(tftd)/units/bigobs.pck", 37),
	pMap = pck_image_ex(true, 32, 48, "$(tftd)/units/floorob.pck", 36),
	health = 999,
	importance = 7,
	width = 2,
	height = 2,
	ammo = {"THERMAL SHOK BOMB"},
	pHeld = pck_image_set_ex(true, 32, 40, "$(tftd)/units/handob.pck", 64, 8),
	accuracy = {0, 70, 120},
	time = {0, 50, 70},
	weight = 8,
	isGun = 1,
	minimapMark = 1,
	twoHanded = 1,
	sound = "alien-small-launch",
}

AddXcomItem {
	cost = 100,
	name = "THERMAL SHOK BOMB",
	pInv = pck_image_ex(true, 32, 48, "$(tftd)/units/bigobs.pck", 38),
	pMap = pck_image_ex(true, 32, 48, "$(tftd)/units/floorob.pck", 81),   
	health = 999,
	damage = 120,
	dDeviation = 100,
	exploRange = 5,
	smokeRange = 5,
	smokeTime = 2,
	importance = 1,
	width = 1,
	height = 1,
	pHeld = pck_image_set_ex(true, 32, 40, "$(tftd)/units/handob.pck", 368, 8),
	damageType = 5,
	rounds = 1,
	disappear = 1,
	weight = 3,
	reloadTime = 15,
}

AddXcomItem {
	cost = 150,
	name = "SONIC PULSER",
	pInv = pck_image_ex(true, 32, 48, "$(tftd)/units/bigobs.pck", 39),
	pMap = pck_image_ex(true, 32, 48, "$(tftd)/units/floorob.pck", 38),
	health = 999,
	damage = 120,
	dDeviation = 100,
	exploRange = 6,
	smokeRange = 6,
	smokeTime = 2,
	importance = 1,
	width = 1,
	height = 1,
	pHeld = pck_image_set_ex(true, 32, 40, "$(tftd)/units/handob.pck", 368, 8),
	damageType = 2,
	isGrenade = 1,
	weight = 3,
	reloadTime = 15,
}

AddXcomItem {
	cost = 80,
	name = "VIBROBLADE",
	pInv = pck_image_ex(true, 32, 48, "$(tftd)/units/bigobs.pck", 60),
	pMap = pck_image_ex(true, 32, 48, "$(tftd)/units/floorob.pck", 75),
	health = 999,
	dDeviation = 100,
	importance = 10,
	width = 2,
	height = 3,
	pHeld = pck_image_set_ex(true, 32, 40, "$(tftd)/units/handob.pck", 168, 8),
	damageType = 0,
	damage = 80,
	weight = 10,
	isWeapon = 1,
	useTime = 25,
	isHandToHand = 1,
	twoHanded = 1, 
}

AddXcomItem {
	cost = 110,
	name = "THERMIC LANCE",
	pInv = pck_image_ex(true, 32, 48, "$(tftd)/units/bigobs.pck", 59),
	pMap = pck_image_ex(true, 32, 48, "$(tftd)/units/floorob.pck", 74),
	health = 999,
	dDeviation = 100,
	importance = 12,
	width = 2,
	height = 3,
	pHeld = pck_image_set_ex(true, 32, 40, "$(tftd)/units/handob.pck", 176, 8),
	damageType = 4,
	damage = 110,
	weight = 10,
	isWeapon = 1,
	useTime = 25,
	isHandToHand = 1,
	twoHanded = 1, 
}

AddXcomItem {
	cost = 150,
	name = "HEAVY THERMIC LANCE",
	pInv = pck_image_ex(true, 32, 48, "$(tftd)/units/bigobs.pck", 58),
	pMap = pck_image_ex(true, 32, 48, "$(tftd)/units/floorob.pck", 73),
	health = 999,
	dDeviation = 100,
	importance = 14,
	width = 2,
	height = 3,
	pHeld = pck_image_set_ex(true, 32, 40, "$(tftd)/units/handob.pck", 184, 8),
	damageType = 4,
	damage = 150,
	weight = 15,
	isWeapon = 1,
	useTime = 25,
	isHandToHand = 1,
	twoHanded = 1, 
}

AddEquipment {
	Name = "Original TFTD Weapon Set",
	Layout = {
		{00, 00, "DART POD"},
		{00, 01, "DART PISTOL"},
		{00, 06, "HYDRO JET CANNON"},
		{01, 00, "HARPOON POD"},
		{01, 01, "HARPOON GUN"},
		{03, 01, "GAUSS PISTOL"},
		{02, 06, "HE-SHELL"},
		{02, 07, "PHOSPHOROUS-SHELL"},
		{02, 08, "AP-SHELL"},
		{04, 01, "GAUSS RIFLE"},
		{05, 01, "HEAVY GAUSS CANNON"},
		{05, 06, "GAS CANNON"},
		{08, 00, "SONIC PISTOL CLIP"},
		{08, 01, "SONIC PISTOL"},
		{09, 00, "BLASTA CLIP"},
		{09, 01, "SONIC BLASTA RIFLE"},
		{07, 06, "EXPLOSIVE BOLT"},
		{07, 07, "PHOSPHOROUS BOLT"},
		{07, 08, "SOLID BOLT"},
		{10, 00, "SONIC CANNON CLIP"},
		{10, 01, "SONIC CANNON"},
		{10, 06, "AQUA JET LAUNCHER"},
		{13, 00, "SONIC PULSER"},
		{14, 00, "MAGNA-BLAST GRENADE"},
		{13, 06, "PHOSPHOROUS TORPEDO"},
		{15, 00, "PARTICLE GRENADE"},
		{16, 02, "THERMAL TAZER"},
		{12, 06, "LARGE TORPEDO"},
		{16, 00, "DYE GRENADE"},
		{13, 02, "THERMAL SHOK BOMB"},
		{13, 03, "THERMAL SHOK CANNON"},
		{14, 06, "SMALL TORPEDO"},
		{18, 00, "MAGNA-PACK"},
		{03, 00, "GAUSS PISTOL CLIP"},
		{04, 00, "GAUSS RIFLE CLIP"},
		{05, 00, "GAUSS CANNON CLIP"},
		{18, 02, "VIBROBLADE"},
		{16, 06, "THERMIC LANCE"},
		{18, 06, "HEAVY THERMIC LANCE"},
	}
}