AddXcomItem {
    cost = 50,
    name = "ZAP PISTOL",
    pInv = png_image("$(extension)/galactic/pInv/zp.png" ),
    pMap = png_image("$(extension)/galactic/pMap/zp.png" ),
    health = 100,
    importance = 5,
    width = 1,
    height = 2,
    ammo = {"ZAP PISTOL CHARGE"},
    pHeld = {
    png_image("$(extension)/galactic/pHeld/zp/32x40-001.png"),
    png_image("$(extension)/galactic/pHeld/zp/32x40-002.png"),
    png_image("$(extension)/galactic/pHeld/zp/32x40-003.png"),
    png_image("$(extension)/galactic/pHeld/zp/32x40-004.png"),
    png_image("$(extension)/galactic/pHeld/zp/32x40-005.png"),
    png_image("$(extension)/galactic/pHeld/zp/32x40-006.png"),
    png_image("$(extension)/galactic/pHeld/zp/32x40-007.png"),
    png_image("$(extension)/galactic/pHeld/zp/32x40-008.png")
    },
    accuracy = {0, 65, 85},
    time = {0, 20, 35},
    weight = 3,
    isGun = 1,
    minimapMark = 1,
    sound = cat_sample("$(xcom)/sound/sound1.cat", 4) or cat_sample("$(xcom)/sound/sample2.cat", 4),
}

AddXcomItem {
    cost = 20,
    name = "ZAP PISTOL CHARGE",
    pInv = png_image("$(extension)/galactic/pInv/zpc.png" ),
    pMap = png_image("$(extension)/galactic/pMap/zc.png" ),
    health = 100,
    damage = 60,
    dDeviation = 50,
    exploRange = 2,
    importance = 3,
    width = 1,
    height = 1,
      pHeld = {
    png_image("$(extension)/galactic/pHeld/zc/32x40-001.png"),
    png_image("$(extension)/galactic/pHeld/zc/32x40-002.png"),
    png_image("$(extension)/galactic/pHeld/zc/32x40-003.png"),
    png_image("$(extension)/galactic/pHeld/zc/32x40-004.png"),
    png_image("$(extension)/galactic/pHeld/zc/32x40-005.png"),
    png_image("$(extension)/galactic/pHeld/zc/32x40-006.png"),
    png_image("$(extension)/galactic/pHeld/zc/32x40-007.png"),
    png_image("$(extension)/galactic/pHeld/zc/32x40-008.png")
      },
    damageType = 5,
    rounds = 14,
    disappear = 0,
    weight = 1,
    isAmmo = 1,
    reloadTime = 15,
    sound = cat_sample("$(xcom)/sound/sound1.cat", 53) or cat_sample("$(xcom)/sound/sample2.cat", 53),
}

AddXcomItem {
    cost = 70,
    name = "ZAP RIFLE",
    pInv = png_image("$(extension)/galactic/pInv/zr.png" ),
    pMap = png_image("$(extension)/galactic/pMap/zr.png" ),
    health = 100,
    importance = 6,
    width = 2,
    height = 3,
    ammo = {"ZAP RIFLE CHARGE"},
    pHeld = {
    png_image("$(extension)/galactic/pHeld/zr/32x40-001.png"),
    png_image("$(extension)/galactic/pHeld/zr/32x40-002.png"),
    png_image("$(extension)/galactic/pHeld/zr/32x40-003.png"),
    png_image("$(extension)/galactic/pHeld/zr/32x40-004.png"),
    png_image("$(extension)/galactic/pHeld/zr/32x40-005.png"),
    png_image("$(extension)/galactic/pHeld/zr/32x40-006.png"),
    png_image("$(extension)/galactic/pHeld/zr/32x40-007.png"),
    png_image("$(extension)/galactic/pHeld/zr/32x40-008.png")
    },
    accuracy = {40, 75, 115},
    time = {12, 25, 80},
    autoShots = 3,
    weight = 5,
    isGun = 1,
    minimapMark = 1,
    twoHanded = 1,
    sound = cat_sample("$(xcom)/sound/sound1.cat", 4) or cat_sample("$(xcom)/sound/sample2.cat", 4),
}

AddXcomItem {
    cost = 25,
    name = "ZAP RIFLE CHARGE",
    pInv = png_image("$(extension)/galactic/pInv/zrc.png", 4),
    pMap = png_image("$(extension)/galactic/pMap/zc.png", 4),
    health = 100,
    damage = 70,
    dDeviation = 60,
    exploRange = 2,
    importance = 1,
    width = 2,
    height = 1,
      pHeld = {
    png_image("$(extension)/galactic/pHeld/zc/32x40-001.png"),
    png_image("$(extension)/galactic/pHeld/zc/32x40-002.png"),
    png_image("$(extension)/galactic/pHeld/zc/32x40-003.png"),
    png_image("$(extension)/galactic/pHeld/zc/32x40-004.png"),
    png_image("$(extension)/galactic/pHeld/zc/32x40-005.png"),
    png_image("$(extension)/galactic/pHeld/zc/32x40-006.png"),
    png_image("$(extension)/galactic/pHeld/zc/32x40-007.png"),
    png_image("$(extension)/galactic/pHeld/zc/32x40-008.png")
      },
    damageType = 5,
    rounds = 26,
    disappear = 0,
    weight = 2,
    isAmmo = 1,
    reloadTime = 15,
    sound = cat_sample("$(xcom)/sound/sound1.cat", 53) or cat_sample("$(xcom)/sound/sample2.cat", 53),
}


AddXcomItem {
    cost = 150,
      name = "LIGHT PHASER",
    pInv = png_image("$(extension)/galactic/pInv/lp.png", 3),
    pMap = png_image("$(extension)/galactic/pMap/lp.png", 5),
    health = 70,
    damage = 40,
    dDeviation = 70,
    importance = 12,
    width = 1,
    height = 2,
      pHeld = {
    png_image("$(extension)/galactic/pHeld/lp/32x40-001.png"),
    png_image("$(extension)/galactic/pHeld/lp/32x40-002.png"),
    png_image("$(extension)/galactic/pHeld/lp/32x40-003.png"),
    png_image("$(extension)/galactic/pHeld/lp/32x40-004.png"),
    png_image("$(extension)/galactic/pHeld/lp/32x40-005.png"),
    png_image("$(extension)/galactic/pHeld/lp/32x40-006.png"),
    png_image("$(extension)/galactic/pHeld/lp/32x40-007.png"),
    png_image("$(extension)/galactic/pHeld/lp/32x40-008.png")
      },
      autoShots = 3,
      damageType = 3,
      accuracy = {35, 47, 0},
      time = {8, 20, 0},
      weight = 6,
      isGun = 1,
    minimapMark = 1,
      sound = cat_sample("$(xcom)/sound/sound1.cat", 11) or cat_sample("$(xcom)/sound/sample2.cat", 11),
}

AddXcomItem {
      cost = 300,
      name = "PULSE PHASER",
      pInv = png_image("$(extension)/galactic/pInv/pp.png", 5),
      pMap = png_image("$(extension)/galactic/pMap/pp.png", 5),
      health = 70,
      damage = 65,
      dDeviation = 50,
      importance = 12,
      width = 1,
      height = 3,
      pHeld = {
    png_image("$(extension)/galactic/pHeld/pp/32x40-001.png"),
    png_image("$(extension)/galactic/pHeld/pp/32x40-002.png"),
    png_image("$(extension)/galactic/pHeld/pp/32x40-003.png"),
    png_image("$(extension)/galactic/pHeld/pp/32x40-004.png"),
    png_image("$(extension)/galactic/pHeld/pp/32x40-005.png"),
    png_image("$(extension)/galactic/pHeld/pp/32x40-006.png"),
    png_image("$(extension)/galactic/pHeld/pp/32x40-007.png"),
    png_image("$(extension)/galactic/pHeld/pp/32x40-008.png")
      },
      damageType = 3,
      accuracy = {50, 70, 100},
      time = {12, 25, 60},
      autoShots = 3,
      weight = 8,
      twoHanded = 1,
      isGun = 1,
    minimapMark = 1,
      sound = cat_sample("$(xcom)/sound/sound1.cat", 11) or cat_sample("$(xcom)/sound/sample2.cat", 11),
}

AddXcomItem {
      cost = 550,
      name = "HEAVY PHASER",
      pInv = png_image("$(extension)/galactic/pInv/hp.png", 3),
      pMap = png_image("$(extension)/galactic/pMap/hp.png", 3),
      health = 70,
      damage = 95,
      dDeviation = 50,
      importance = 12,
      width = 1,
      height = 3,
      pHeld = {
    png_image("$(extension)/galactic/pHeld/hp/32x40-001.png"),
    png_image("$(extension)/galactic/pHeld/hp/32x40-002.png"),
    png_image("$(extension)/galactic/pHeld/hp/32x40-003.png"),
    png_image("$(extension)/galactic/pHeld/hp/32x40-004.png"),
    png_image("$(extension)/galactic/pHeld/hp/32x40-005.png"),
    png_image("$(extension)/galactic/pHeld/hp/32x40-006.png"),
    png_image("$(extension)/galactic/pHeld/hp/32x40-007.png"),
    png_image("$(extension)/galactic/pHeld/hp/32x40-008.png")
      },
      damageType = 3,
      accuracy = {0, 86, 120},
      time = {0, 40, 70},
      weight = 13,
      twoHanded = 1,
      isGun = 1,
    minimapMark = 1,
      sound = cat_sample("$(xcom)/sound/sound1.cat", 11) or cat_sample("$(xcom)/sound/sample2.cat", 11),
}

AddXcomItem {
    cost = 400,
    name = "PHASER CANNON",
    pInv = png_image("$(extension)/galactic/pInv/pc.png", 3),
      pMap = png_image("$(extension)/galactic/pMap/pc.png", 3),
    health = 70,
    damage = 75,
    dDeviation = 50,
    importance = 7,
    width = 2,
    height = 3,
      pHeld = {
    png_image("$(extension)/galactic/pHeld/pc/32x40-001.png"),
    png_image("$(extension)/galactic/pHeld/pc/32x40-002.png"),
    png_image("$(extension)/galactic/pHeld/pc/32x40-003.png"),
    png_image("$(extension)/galactic/pHeld/pc/32x40-004.png"),
    png_image("$(extension)/galactic/pHeld/pc/32x40-005.png"),
    png_image("$(extension)/galactic/pHeld/pc/32x40-006.png"),
    png_image("$(extension)/galactic/pHeld/pc/32x40-007.png"),
    png_image("$(extension)/galactic/pHeld/pc/32x40-008.png")
      },
    damageType = 3,
    accuracy = {35, 55, 0},
    time = {10, 50, 0},
    autoShots = 5,
    weight = 30,
    isShootable = 1,
    isWeapon = 1,
    isGun = 1,
    minimapMark = 1,
    twoHanded = 1,
    sound = cat_sample("$(xcom)/sound/sound1.cat", 11) or cat_sample("$(xcom)/sound/sample2.cat", 11),
}

AddXcomItem {
      cost = 150,
      name = "MEZON PISTOL",
      pInv = png_image("$(extension)/galactic/pInv/mp.png", 32),
      pMap = png_image("$(extension)/galactic/pMap/mp.png", 32),
      health = 60,
      importance = 4,
      width = 1,
      height = 2,
      ammo = {"MEZON PISTOL CHARGE"},
      pHeld = {
    png_image("$(extension)/galactic/pHeld/mp/32x40-001.png"),
    png_image("$(extension)/galactic/pHeld/mp/32x40-002.png"),
    png_image("$(extension)/galactic/pHeld/mp/32x40-003.png"),
    png_image("$(extension)/galactic/pHeld/mp/32x40-004.png"),
    png_image("$(extension)/galactic/pHeld/mp/32x40-005.png"),
    png_image("$(extension)/galactic/pHeld/mp/32x40-006.png"),
    png_image("$(extension)/galactic/pHeld/mp/32x40-007.png"),
    png_image("$(extension)/galactic/pHeld/mp/32x40-008.png")
      },
      accuracy = {45, 60, 80},
      time = {10, 30, 60},
      autoShots = 3,
      weight = 3,
      isGun = 1,
    minimapMark = 1,
      sound = cat_sample("$(xcom)/sound/sound1.cat", 18) or cat_sample("$(xcom)/sound/sample2.cat", 18),
}

AddXcomItem {
      cost = 60,
      name = "MEZON PISTOL CHARGE",
      pInv = png_image("$(extension)/galactic/pInv/mpc.png", 34),
      pMap = png_image("$(extension)/galactic/pMap/mc.png", 34),
      health = 70,
      damage = 57,
      dDeviation = 25,
      importance = 1,
      width = 1,
      height = 1,
      pHeld = {
    png_image("$(extension)/galactic/pHeld/mc/32x40-001.png"),
    png_image("$(extension)/galactic/pHeld/mc/32x40-002.png"),
    png_image("$(extension)/galactic/pHeld/mc/32x40-003.png"),
    png_image("$(extension)/galactic/pHeld/mc/32x40-004.png"),
    png_image("$(extension)/galactic/pHeld/mc/32x40-005.png"),
    png_image("$(extension)/galactic/pHeld/mc/32x40-006.png"),
    png_image("$(extension)/galactic/pHeld/mc/32x40-007.png"),
    png_image("$(extension)/galactic/pHeld/mc/32x40-008.png")
      },
      damageType = 4,
      rounds = 20,
      disappear = 0,
      weight = 2,
      isAmmo = 1,
      reloadTime = 15,
      sound = cat_sample("$(xcom)/sound/sound1.cat", 19) or cat_sample("$(xcom)/sound/sample2.cat", 19),
}

AddXcomItem {
      cost = 400,
      name = "MEZON RIFLE",
      pInv = png_image("$(extension)/galactic/pInv/mr.png", 32),
      pMap = png_image("$(extension)/galactic/pMap/mr.png", 32),
      health = 60,
      importance = 4,
      width = 1,
      height = 3,
      ammo = {"MEZON RIFLE CHARGE"},
      pHeld = {
    png_image("$(extension)/galactic/pHeld/mr/32x40-001.png"),
    png_image("$(extension)/galactic/pHeld/mr/32x40-002.png"),
    png_image("$(extension)/galactic/pHeld/mr/32x40-003.png"),
    png_image("$(extension)/galactic/pHeld/mr/32x40-004.png"),
    png_image("$(extension)/galactic/pHeld/mr/32x40-005.png"),
    png_image("$(extension)/galactic/pHeld/mr/32x40-006.png"),
    png_image("$(extension)/galactic/pHeld/mr/32x40-007.png"),
    png_image("$(extension)/galactic/pHeld/mr/32x40-008.png")
      },
      accuracy = {50, 81, 95},
      time = {12, 30, 60},
      autoShots = 3,
      weight = 5,
      twoHanded = 1,
      isGun = 1,
    minimapMark = 1,
      sound = cat_sample("$(xcom)/sound/sound1.cat", 18) or cat_sample("$(xcom)/sound/sample2.cat", 18),
}

AddXcomItem {
      cost = 100,
      name = "MEZON RIFLE CHARGE",
      pInv = png_image("$(extension)/galactic/pInv/mrc.png", 34),
      pMap = png_image("$(extension)/galactic/pMap/mc.png", 34),
      health = 60,
      damage = 86,
      dDeviation = 25,
      importance = 1,
      width = 1,
      height = 1,
      pHeld = {
    png_image("$(extension)/galactic/pHeld/mc/32x40-001.png"),
    png_image("$(extension)/galactic/pHeld/mc/32x40-002.png"),
    png_image("$(extension)/galactic/pHeld/mc/32x40-003.png"),
    png_image("$(extension)/galactic/pHeld/mc/32x40-004.png"),
    png_image("$(extension)/galactic/pHeld/mc/32x40-005.png"),
    png_image("$(extension)/galactic/pHeld/mc/32x40-006.png"),
    png_image("$(extension)/galactic/pHeld/mc/32x40-007.png"),
    png_image("$(extension)/galactic/pHeld/mc/32x40-008.png")
      },
      damageType = 4,
      rounds = 22,
      disappear = 0,
      weight = 3,
      isAmmo = 1,
      reloadTime = 15,
      sound = cat_sample("$(xcom)/sound/sound1.cat", 19) or cat_sample("$(xcom)/sound/sample2.cat", 19),
}

AddXcomItem {
      cost = 300,
      name = "HEAVY MEZON",
      pInv = png_image("$(extension)/galactic/pInv/hm.png", 32),
      pMap = png_image("$(extension)/galactic/pMap/hm.png", 32),
      health = 60,
      importance = 4,
      width = 2,
      height = 3,
      ammo = {"HEAVY MEZON CHARGE"},
      pHeld = {
    png_image("$(extension)/galactic/pHeld/hm/32x40-001.png"),
    png_image("$(extension)/galactic/pHeld/hm/32x40-002.png"),
    png_image("$(extension)/galactic/pHeld/hm/32x40-003.png"),
    png_image("$(extension)/galactic/pHeld/hm/32x40-004.png"),
    png_image("$(extension)/galactic/pHeld/hm/32x40-005.png"),
    png_image("$(extension)/galactic/pHeld/hm/32x40-006.png"),
    png_image("$(extension)/galactic/pHeld/hm/32x40-007.png"),
    png_image("$(extension)/galactic/pHeld/hm/32x40-008.png")
      },
      accuracy = { 0, 50, 105},
      time = { 0, 30, 55},
      autoShots = 3,
      weight = 16,
      twoHanded = 1,
      isGun = 1,
    minimapMark = 1,
      sound = cat_sample("$(xcom)/sound/sound1.cat", 18) or cat_sample("$(xcom)/sound/sample2.cat", 18),
}

AddXcomItem {
      cost = 75,
      name = "HEAVY MEZON CHARGE",
      pInv = png_image("$(extension)/galactic/pInv/hmc.png", 34),
      pMap = png_image("$(extension)/galactic/pMap/mc.png", 34),
      health = 60,
      damage = 121,
      dDeviation = 25,
      importance = 1,
      width = 1,
      height = 1,
      pHeld = {
    png_image("$(extension)/galactic/pHeld/mc/32x40-001.png"),
    png_image("$(extension)/galactic/pHeld/mc/32x40-002.png"),
    png_image("$(extension)/galactic/pHeld/mc/32x40-003.png"),
    png_image("$(extension)/galactic/pHeld/mc/32x40-004.png"),
    png_image("$(extension)/galactic/pHeld/mc/32x40-005.png"),
    png_image("$(extension)/galactic/pHeld/mc/32x40-006.png"),
    png_image("$(extension)/galactic/pHeld/mc/32x40-007.png"),
    png_image("$(extension)/galactic/pHeld/mc/32x40-008.png")
      },
      damageType = 4,
      reloadTime = 15,
      rounds = 10,
      disappear = 0,
      weight = 3,
      isAmmo = 1,
      sound = cat_sample("$(xcom)/sound/sound1.cat", 19) or cat_sample("$(xcom)/sound/sample2.cat", 19),
}

AddXcomItem {
      cost = 250,
      name = "ANTI-MATTER GUN",
      pInv = png_image("$(extension)/galactic/pInv/amg.png", 32),
      pMap = png_image("$(extension)/galactic/pMap/amg.png", 32),
      health = 60,
      importance = 4,
      width = 1,
      height = 2,
      ammo = {"ANTI-MATTER GUN CHARGE"},
      pHeld = {
    png_image("$(extension)/galactic/pHeld/amg/32x40-001.png"),
    png_image("$(extension)/galactic/pHeld/amg/32x40-002.png"),
    png_image("$(extension)/galactic/pHeld/amg/32x40-003.png"),
    png_image("$(extension)/galactic/pHeld/amg/32x40-004.png"),
    png_image("$(extension)/galactic/pHeld/amg/32x40-005.png"),
    png_image("$(extension)/galactic/pHeld/amg/32x40-006.png"),
    png_image("$(extension)/galactic/pHeld/amg/32x40-007.png"),
    png_image("$(extension)/galactic/pHeld/amg/32x40-008.png")
      },
      accuracy = { 45, 65, 0},
      time = { 15, 38, 0},
      autoShots = 3,
      weight = 12,
      isGun = 1,
    minimapMark = 1,
      sound = cat_sample("$(xcom)/sound/sound1.cat", 53) or cat_sample("$(xcom)/sound/sample2.cat", 53),
}

AddXcomItem {
      cost = 150,
      name = "ANTI-MATTER GUN CHARGE",
      pInv = png_image("$(extension)/galactic/pInv/amgc.png", 34),
      pMap = png_image("$(extension)/galactic/pMap/amc.png", 34),
      health = 60,
      damage = 75,
      dDeviation = 25,
      importance = 1,
      width = 1,
      height = 1,
      pHeld = {
    png_image("$(extension)/galactic/pHeld/amc/32x40-001.png"),
    png_image("$(extension)/galactic/pHeld/amc/32x40-002.png"),
    png_image("$(extension)/galactic/pHeld/amc/32x40-003.png"),
    png_image("$(extension)/galactic/pHeld/amc/32x40-004.png"),
    png_image("$(extension)/galactic/pHeld/amc/32x40-005.png"),
    png_image("$(extension)/galactic/pHeld/amc/32x40-006.png"),
    png_image("$(extension)/galactic/pHeld/amc/32x40-007.png"),
    png_image("$(extension)/galactic/pHeld/amc/32x40-008.png")
      },
      damageType = 1,
      exploRange = 2,
      smokeRange = 2,
      smokeTime = 2,
      rounds = 12,
      disappear = 0,
      weight = 2,
      isAmmo = 1,
      reloadTime = 15,
      sound = cat_sample("$(xcom)/sound/sound1.cat", 19) or cat_sample("$(xcom)/sound/sample2.cat", 19),
}

AddXcomItem {
      cost = 500,
      name = "ANTI-MATTER BLASTER",
      pInv = png_image("$(extension)/galactic/pInv/amb.png", 32),
      pMap = png_image("$(extension)/galactic/pMap/amb.png", 32),
      health = 60,
      importance = 4,
      width = 1,
      height = 3,
      ammo = {"ANTI-MATTER BLASTER CHARGE"},
      pHeld = {
    png_image("$(extension)/galactic/pHeld/amb/32x40-001.png"),
    png_image("$(extension)/galactic/pHeld/amb/32x40-002.png"),
    png_image("$(extension)/galactic/pHeld/amb/32x40-003.png"),
    png_image("$(extension)/galactic/pHeld/amb/32x40-004.png"),
    png_image("$(extension)/galactic/pHeld/amb/32x40-005.png"),
    png_image("$(extension)/galactic/pHeld/amb/32x40-006.png"),
    png_image("$(extension)/galactic/pHeld/amb/32x40-007.png"),
    png_image("$(extension)/galactic/pHeld/amb/32x40-008.png")
      },
      accuracy = { 0, 50, 100},
      time = { 0, 35, 75},
      weight = 16,
      isGun = 1,
    minimapMark = 1,
      twoHanded = 1,
      sound = cat_sample("$(xcom)/sound/sound1.cat", 53) or cat_sample("$(xcom)/sound/sample2.cat", 53),
}

AddXcomItem {
      cost = 300,
      name = "ANTI-MATTER BLASTER CHARGE",
      pInv = png_image("$(extension)/galactic/pInv/ambc.png", 34),
      pMap = png_image("$(extension)/galactic/pMap/amc.png", 34),
      health = 60,
      damage = 120,
      dDeviation = 25,
      importance = 1,
      width = 1,
      height = 1,
      pHeld = {
    png_image("$(extension)/galactic/pHeld/amc/32x40-001.png"),
    png_image("$(extension)/galactic/pHeld/amc/32x40-002.png"),
    png_image("$(extension)/galactic/pHeld/amc/32x40-003.png"),
    png_image("$(extension)/galactic/pHeld/amc/32x40-004.png"),
    png_image("$(extension)/galactic/pHeld/amc/32x40-005.png"),
    png_image("$(extension)/galactic/pHeld/amc/32x40-006.png"),
    png_image("$(extension)/galactic/pHeld/amc/32x40-007.png"),
    png_image("$(extension)/galactic/pHeld/amc/32x40-008.png")
      },
      damageType = 1,
      exploRange = 2,
      smokeRange = 2,
      smokeTime = 2,
      rounds = 8,
      disappear = 0,
      weight = 3,
      isAmmo = 1,
      reloadTime = 15,
      sound = cat_sample("$(xcom)/sound/sound1.cat", 19) or cat_sample("$(xcom)/sound/sample2.cat", 19),
}

AddXcomItem {
      cost = 200,
      name = "OMEGA LAUNCHER",
      pInv = png_image("$(extension)/galactic/pInv/ol.png", 38),
      pMap = png_image("$(extension)/galactic/pMap/ol.png", 38),
      health = 50,
      importance = 16,
      width = 2,
      height = 3,
      ammo = {"ALIEN MISSILE", "ALIEN MISSILE POD", "ALIEN SMOKE POD"},
      pHeld = {
    png_image("$(extension)/galactic/pHeld/ol/32x40-001.png"),
    png_image("$(extension)/galactic/pHeld/ol/32x40-002.png"),
    png_image("$(extension)/galactic/pHeld/ol/32x40-003.png"),
    png_image("$(extension)/galactic/pHeld/ol/32x40-004.png"),
    png_image("$(extension)/galactic/pHeld/ol/32x40-005.png"),
    png_image("$(extension)/galactic/pHeld/ol/32x40-006.png"),
    png_image("$(extension)/galactic/pHeld/ol/32x40-007.png"),
    png_image("$(extension)/galactic/pHeld/ol/32x40-008.png")
      },
      accuracy = {35, 50, 120},
      time = {20, 35, 80},
      autoShots = 3,
      weight = 13,
      isGun = 1,
    minimapMark = 1,
    twoHanded = 1,
      sound = cat_sample("$(xcom)/sound/sound1.cat", 53) or cat_sample("$(xcom)/sound/sample2.cat", 53),
}

AddXcomItem {
      cost = 400,
      name = "ALIEN MISSILE",
      pInv = png_image("$(extension)/galactic/pInv/olm.png", 38),
      pMap = png_image("$(extension)/galactic/pMap/olm.png", 38),   
      health = 60,
      damage = 110,
      dDeviation = 50,
      exploRange = 6,
      smokeRange = 0,
      smokeTime = 0,
      importance = 1,
      width = 1,
      height = 1,
      pHeld = {
    png_image("$(extension)/galactic/pHeld/mc/32x40-001.png"),
    png_image("$(extension)/galactic/pHeld/mc/32x40-002.png"),
    png_image("$(extension)/galactic/pHeld/mc/32x40-003.png"),
    png_image("$(extension)/galactic/pHeld/mc/32x40-004.png"),
    png_image("$(extension)/galactic/pHeld/mc/32x40-005.png"),
    png_image("$(extension)/galactic/pHeld/mc/32x40-006.png"),
    png_image("$(extension)/galactic/pHeld/mc/32x40-007.png"),
    png_image("$(extension)/galactic/pHeld/mc/32x40-008.png")
      },
      damageType = 2,
      rounds = 1,
      disappear = 1,
      weight = 5,
      isAmmo = 1,
      reloadTime = 15,
}

AddXcomItem {
      cost = 300,
      name = "ALIEN MISSILE POD",
      pInv = png_image("$(extension)/galactic/pInv/olp.png", 38),
      pMap = png_image("$(extension)/galactic/pMap/olp.png", 38), 
      health = 60,
      damage = 90,
      dDeviation = 50,
      exploRange = 3,
      smokeRange = 0,
      smokeTime = 0,
      importance = 1,
      width = 1,
      height = 1,
      pHeld = {
    png_image("$(extension)/galactic/pHeld/mc/32x40-001.png"),
    png_image("$(extension)/galactic/pHeld/mc/32x40-002.png"),
    png_image("$(extension)/galactic/pHeld/mc/32x40-003.png"),
    png_image("$(extension)/galactic/pHeld/mc/32x40-004.png"),
    png_image("$(extension)/galactic/pHeld/mc/32x40-005.png"),
    png_image("$(extension)/galactic/pHeld/mc/32x40-006.png"),
    png_image("$(extension)/galactic/pHeld/mc/32x40-007.png"),
    png_image("$(extension)/galactic/pHeld/mc/32x40-008.png")
      },
      damageType = 2,
      rounds = 6,
      disappear = 1,
      weight = 5,
      isAmmo = 1,
      reloadTime = 15,
}

AddXcomItem {
      cost = 125,
      name = "ALIEN SMOKE POD",
      pInv = png_image("$(extension)/galactic/pInv/olsm.png", 3),
      pMap = png_image("$(extension)/galactic/pMap/olsm.png", 3),
      health = 100,
      damage = 5,
      dDeviation = 50,
      exploRange = 1,
      smokeRange = 5,
      smokeTime = 4,
      importance = 5,
      width = 1,
      height = 1,
      pHeld = {
    png_image("$(extension)/galactic/pHeld/mc/32x40-001.png"),
    png_image("$(extension)/galactic/pHeld/mc/32x40-002.png"),
    png_image("$(extension)/galactic/pHeld/mc/32x40-003.png"),
    png_image("$(extension)/galactic/pHeld/mc/32x40-004.png"),
    png_image("$(extension)/galactic/pHeld/mc/32x40-005.png"),
    png_image("$(extension)/galactic/pHeld/mc/32x40-006.png"),
    png_image("$(extension)/galactic/pHeld/mc/32x40-007.png"),
    png_image("$(extension)/galactic/pHeld/mc/32x40-008.png")
      },
      damageType = 2,
      rounds = 6,
      disappear = 1,
      weight = 3,
      isAmmo = 1,
      reloadTime = 12,
}

AddXcomItem {
      cost = 100,
      name = "ELECTRIC KNIFE",
      pInv = png_image("$(extension)/galactic/pInv/ek.png", 4),
      pMap = png_image("$(extension)/galactic/pMap/ek.png", 4),
      health = 80,
      damage = 100,
      dDeviation = 25,
      importance = 6,
      width = 1,
      height = 2,
      pHeld = {
    png_image("$(extension)/galactic/pHeld/ek/32x40-001.png"),
    png_image("$(extension)/galactic/pHeld/ek/32x40-002.png"),
    png_image("$(extension)/galactic/pHeld/ek/32x40-003.png"),
    png_image("$(extension)/galactic/pHeld/ek/32x40-004.png"),
    png_image("$(extension)/galactic/pHeld/ek/32x40-005.png"),
    png_image("$(extension)/galactic/pHeld/ek/32x40-006.png"),
    png_image("$(extension)/galactic/pHeld/ek/32x40-007.png"),
    png_image("$(extension)/galactic/pHeld/ek/32x40-008.png")
      },
    useTime = 15,
      damageType = 5,
      weight = 3,
      isHandToHand = 1,
}

AddXcomItem {
      cost = 100,
      name = "PLASMA KNIFE",
      pInv = png_image("$(extension)/galactic/pInv/pk.png", 4),
      pMap = png_image("$(extension)/galactic/pMap/pk.png", 4),
      health = 80,
      damage = 100,
      dDeviation = 25,
      importance = 6,
      width = 1,
      height = 2,
      pHeld = {
    png_image("$(extension)/galactic/pHeld/pk/32x40-001.png"),
    png_image("$(extension)/galactic/pHeld/pk/32x40-002.png"),
    png_image("$(extension)/galactic/pHeld/pk/32x40-003.png"),
    png_image("$(extension)/galactic/pHeld/pk/32x40-004.png"),
    png_image("$(extension)/galactic/pHeld/pk/32x40-005.png"),
    png_image("$(extension)/galactic/pHeld/pk/32x40-006.png"),
    png_image("$(extension)/galactic/pHeld/pk/32x40-007.png"),
    png_image("$(extension)/galactic/pHeld/pk/32x40-008.png")
      },
    useTime = 15,
      damageType = 0,
      weight = 3,
      isHandToHand = 1,
}

AddXcomItem {
      cost = 150,
      name = "BEAM BLADE",
      pInv = png_image("$(extension)/galactic/pInv/bb.png", 4),
      pMap = png_image("$(extension)/galactic/pMap/bb.png", 4),
      health = 80,
      damage = 150,
      dDeviation = 25,
      importance = 6,
      width = 1,
      height = 3,
      pHeld = {
    png_image("$(extension)/galactic/pHeld/bb/32x40-001.png"),
    png_image("$(extension)/galactic/pHeld/bb/32x40-002.png"),
    png_image("$(extension)/galactic/pHeld/bb/32x40-003.png"),
    png_image("$(extension)/galactic/pHeld/bb/32x40-004.png"),
    png_image("$(extension)/galactic/pHeld/bb/32x40-005.png"),
    png_image("$(extension)/galactic/pHeld/bb/32x40-006.png"),
    png_image("$(extension)/galactic/pHeld/bb/32x40-007.png"),
    png_image("$(extension)/galactic/pHeld/bb/32x40-008.png")
      },
    useTime = 20,
      damageType = 0,
      weight = 5,
      isHandToHand = 1,
}

AddXcomItem {
      cost = 500,
      name = "DISC LAUNCHER",
      pInv = png_image("$(extension)/galactic/pInv/dl.png", 38),
      pMap = png_image("$(extension)/galactic/pMap/dl.png", 38),
      health = 50,
      importance = 16,
      width = 2,
      height = 3,
      ammo = {"PHAZED DISC", "MAGMIZE DISC", "FOG DISC", "SPARK-WAVE DISC"},
      pHeld = {
    png_image("$(extension)/galactic/pHeld/dl/32x40-001.png"),
    png_image("$(extension)/galactic/pHeld/dl/32x40-002.png"),
    png_image("$(extension)/galactic/pHeld/dl/32x40-003.png"),
    png_image("$(extension)/galactic/pHeld/dl/32x40-004.png"),
    png_image("$(extension)/galactic/pHeld/dl/32x40-005.png"),
    png_image("$(extension)/galactic/pHeld/dl/32x40-006.png"),
    png_image("$(extension)/galactic/pHeld/dl/32x40-007.png"),
    png_image("$(extension)/galactic/pHeld/dl/32x40-008.png")
      },
      accuracy = {0, 65, 110},
      time = {0, 40, 75},
      weight = 10,
      isGun = 1,
    minimapMark = 1,
      twoHanded = 1,
      sound = cat_sample("$(xcom)/sound/sound1.cat", 53) or cat_sample("$(xcom)/sound/sample2.cat", 53),
}

AddXcomItem {
    cost = 125,
    name = "PHAZED DISC",
      pInv = png_image("$(extension)/galactic/pInv/pd.png", 4),
      pMap = png_image("$(extension)/galactic/pMap/disc.png", 4),
    health = 60,
    damage = 90,
    dDeviation = 50,
    exploRange = 6,
    smokeRange = 6,
    smokeTime = 2,
    importance = 1,
    width = 1,
    height = 1,
      pHeld = {
    png_image("$(extension)/galactic/pHeld/disc/32x40-001.png"),
    png_image("$(extension)/galactic/pHeld/disc/32x40-002.png"),
    png_image("$(extension)/galactic/pHeld/disc/32x40-003.png"),
    png_image("$(extension)/galactic/pHeld/disc/32x40-004.png"),
    png_image("$(extension)/galactic/pHeld/disc/32x40-005.png"),
    png_image("$(extension)/galactic/pHeld/disc/32x40-006.png"),
    png_image("$(extension)/galactic/pHeld/disc/32x40-007.png"),
    png_image("$(extension)/galactic/pHeld/disc/32x40-008.png")
      },
    damageType = 2,
    isGrenade = 1,
    rounds = 1,
    disappear = 1,
    weight = 3,
    reloadTime = 15,
}

AddXcomItem {
    cost = 60,
    name = "MAGMIZE DISC",
      pInv = png_image("$(extension)/galactic/pInv/md.png", 4),
      pMap = png_image("$(extension)/galactic/pMap/disc.png", 4), 
    health = 50,
    damage = 45,
    dDeviation = 50,
    exploRange = 4,
    smokeRange = 2,
    smokeTime = 2,
    importance = 1,
    width = 1,
    height = 1,
      pHeld = {
    png_image("$(extension)/galactic/pHeld/disc/32x40-001.png"),
    png_image("$(extension)/galactic/pHeld/disc/32x40-002.png"),
    png_image("$(extension)/galactic/pHeld/disc/32x40-003.png"),
    png_image("$(extension)/galactic/pHeld/disc/32x40-004.png"),
    png_image("$(extension)/galactic/pHeld/disc/32x40-005.png"),
    png_image("$(extension)/galactic/pHeld/disc/32x40-006.png"),
    png_image("$(extension)/galactic/pHeld/disc/32x40-007.png"),
    png_image("$(extension)/galactic/pHeld/disc/32x40-008.png")
      },
    damageType = 2,
    isGrenade = 1,
    rounds = 1,
    disappear = 1,
    weight = 2,
    reloadTime = 15,
}

AddXcomItem {
    cost = 30,
    name = "CLOAKED DISC MINE",
      pInv = png_image("$(extension)/galactic/pInv/cdm.png", 4),
      pMap = png_image("$(extension)/galactic/pMap/cdm.png", 4), 
    health = 40,
    damage = 20,
    dDeviation = 50,
    exploRange = 3,
    smokeRange = 3,
    smokeTime = 2,
    importance = 1,
    width = 1,
    height = 1,
      pHeld = {
    png_image("$(extension)/galactic/pHeld/disc/32x40-001.png"),
    png_image("$(extension)/galactic/pHeld/disc/32x40-002.png"),
    png_image("$(extension)/galactic/pHeld/disc/32x40-003.png"),
    png_image("$(extension)/galactic/pHeld/disc/32x40-004.png"),
    png_image("$(extension)/galactic/pHeld/disc/32x40-005.png"),
    png_image("$(extension)/galactic/pHeld/disc/32x40-006.png"),
    png_image("$(extension)/galactic/pHeld/disc/32x40-007.png"),
    png_image("$(extension)/galactic/pHeld/disc/32x40-008.png")
      },
    damageType = 2,
    isGrenade = 1,
    isProximityGrenade = 1,
    disappear = 1,
    weight = 3,
}

AddXcomItem {
    cost = 20,
    name = "FOG DISC",
      pInv = png_image("$(extension)/galactic/pInv/fd.png", 4),
      pMap = png_image("$(extension)/galactic/pMap/disc.png", 4),
    health = 50,
    exploRange = 0,
    smokeRange = 4,
    smokeTime = 6,
    importance = 1,
    width = 1,
    height = 1,
      pHeld = {
    png_image("$(extension)/galactic/pHeld/disc/32x40-001.png"),
    png_image("$(extension)/galactic/pHeld/disc/32x40-002.png"),
    png_image("$(extension)/galactic/pHeld/disc/32x40-003.png"),
    png_image("$(extension)/galactic/pHeld/disc/32x40-004.png"),
    png_image("$(extension)/galactic/pHeld/disc/32x40-005.png"),
    png_image("$(extension)/galactic/pHeld/disc/32x40-006.png"),
    png_image("$(extension)/galactic/pHeld/disc/32x40-007.png"),
    png_image("$(extension)/galactic/pHeld/disc/32x40-008.png")
      },
    damageType = 2,
    isGrenade = 1,
    rounds = 1,
    disappear = 1,
    weight = 2,
    reloadTime = 15,
}

AddXcomItem {
      cost = 75,
      name = "SPARK-WAVE DISC",
      pInv = png_image("$(extension)/galactic/pInv/swd.png", 4),
      pMap = png_image("$(extension)/galactic/pMap/disc.png", 4),
      health = 50,
      damage = 50,
      dDeviation = 25,
      exploRange = 7,
      smokeRange = 5,
      smokeTime = 2,
      importance = 1,
      width = 1,
      height = 1,
      pHeld = {
      png_image("$(extension)/galactic/pHeld/disc/32x40-001.png"),
      png_image("$(extension)/galactic/pHeld/disc/32x40-002.png"),
      png_image("$(extension)/galactic/pHeld/disc/32x40-003.png"),
      png_image("$(extension)/galactic/pHeld/disc/32x40-004.png"),
      png_image("$(extension)/galactic/pHeld/disc/32x40-005.png"),
      png_image("$(extension)/galactic/pHeld/disc/32x40-006.png"),
      png_image("$(extension)/galactic/pHeld/disc/32x40-007.png"),
      png_image("$(extension)/galactic/pHeld/disc/32x40-008.png")
      },
      damageType = 5,
      isGrenade = 1,
      rounds = 1,
    disappear = 1,
      weight = 3,
      reloadTime = 15,
}

AddXcomItem {
    cost = 95,
    name = "HYPER DISC",
      pInv = png_image("$(extension)/galactic/pInv/hd.png", 4),
      pMap = png_image("$(extension)/galactic/pMap/disc.png", 4),
    health = 40,
    damage = 110,
    dDeviation = 50,
    exploRange = 6,
    smokeRange = 6,
    smokeTime = 2,
    importance = 4,
    width = 2,
    height = 1,
      pHeld = {
      png_image("$(extension)/galactic/pHeld/disc/32x40-001.png"),
      png_image("$(extension)/galactic/pHeld/disc/32x40-002.png"),
      png_image("$(extension)/galactic/pHeld/disc/32x40-003.png"),
      png_image("$(extension)/galactic/pHeld/disc/32x40-004.png"),
      png_image("$(extension)/galactic/pHeld/disc/32x40-005.png"),
      png_image("$(extension)/galactic/pHeld/disc/32x40-006.png"),
      png_image("$(extension)/galactic/pHeld/disc/32x40-007.png"),
      png_image("$(extension)/galactic/pHeld/disc/32x40-008.png")
      },
    damageType = 2,
    isGrenade = 1,
    isHighExplosive = 1,
    disappear = 1,
    weight = 6,
}

AddXcomItem {
      cost = 300,
      name = "PF DISC",
      pInv = png_image("$(extension)/galactic/pInv/pfd.png", 4),
      pMap = png_image("$(extension)/galactic/pMap/disc.png", 4),
      health = 200,
      damage = 200,
      dDeviation = 99,
      exploRange = 2,
      smokeRange = 1,
      smokeTime = 2,
      importance = 1,
      width = 1,
      height = 1,
      pHeld = {
      png_image("$(extension)/galactic/pHeld/disc/32x40-001.png"),
      png_image("$(extension)/galactic/pHeld/disc/32x40-002.png"),
      png_image("$(extension)/galactic/pHeld/disc/32x40-003.png"),
      png_image("$(extension)/galactic/pHeld/disc/32x40-004.png"),
      png_image("$(extension)/galactic/pHeld/disc/32x40-005.png"),
      png_image("$(extension)/galactic/pHeld/disc/32x40-006.png"),
      png_image("$(extension)/galactic/pHeld/disc/32x40-007.png"),
      png_image("$(extension)/galactic/pHeld/disc/32x40-008.png")
      },
      damageType = 2,
      isGrenade = 1,
      isProximityGrenade = 1,
    disappear = 1,
      weight = 7,
}

AddEquipment {
    Name = "Galactic",
    Layout = {
        {00, 01, "ZAP PISTOL"},
        {00, 00, "ZAP PISTOL CHARGE"},
        {01, 01, "ZAP RIFLE"},
        {01, 00, "ZAP RIFLE CHARGE"},
        {03, 01, "LIGHT PHASER"},
        {04, 01, "PULSE PHASER"},
        {05, 01, "HEAVY PHASER"},
        {06, 01, "PHASER CANNON"},
        {08, 01, "MEZON PISTOL"},
        {08, 00, "MEZON PISTOL CHARGE"},
        {09, 01, "MEZON RIFLE"},
        {09, 00, "MEZON RIFLE CHARGE"},
        {10, 01, "HEAVY MEZON"},
        {10, 00, "HEAVY MEZON CHARGE"},  
        {00, 05, "ANTI-MATTER GUN"},
        {00, 04, "ANTI-MATTER GUN CHARGE"},
        {01, 05, "ANTI-MATTER BLASTER"},
        {01, 04, "ANTI-MATTER BLASTER CHARGE"},
        {05, 05, "OMEGA LAUNCHER"},
        {07, 07, "ALIEN MISSILE"},
        {07, 05, "ALIEN MISSILE POD"},
        {07, 06, "ALIEN SMOKE POD"},
        {12, 01, "ELECTRIC KNIFE"},
        {13, 01, "PLASMA KNIFE"},
        {14, 01, "BEAM BLADE"},
        {15, 01, "DISC LAUNCHER"},
        {11, 00, "PHAZED DISC"},
        {12, 00, "MAGMIZE DISC"},
        {13, 00, "CLOAKED DISC MINE"},
        {14, 00, "FOG DISC"},
        {15, 00, "SPARK-WAVE DISC"},
        {16, 00, "HYPER DISC"},
        {15, 00, "PF DISC"},
        
    }
}
